esphome:
  name: proscenic-t21
  friendly_name: Proscenic T21

packages:
  t21: github://micasadomotica/proscenic-t21-esphome/packages/proscenic-t21-es-celsius.yaml@v1.0.0

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  encryption:
    key: !secret t21_api_key

ota:
  - platform: esphome
    password: !secret t21_ota_password
